baseurl         = "https://azccb.org"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Azerbaijan Cultural Center Boston"
  subtitle    = "The website of AZCCB -- Azerbaijan Cultural Center Boston"

  cover       = "sky.jpeg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "Azccboston"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = ""
  orgName = "AZCC Boston"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "azccb"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Events"
  url = "/tags/event/"
  weight = 100

[[menu.main]]
  name = "About Us"
  url = "/categories/about-us/"
  weight = 99
